### ISSUE TITLE
Wandb - Format spaces to "-"

### ISSUE THREAD

**Issue by MrCrystAll** [MrCrystAll/Void_CPP#32]
Wandb recently changed their formatting and it looks like spaces tend to mess up the ordering and division of metrics

Let's modify every key encountered to replace spaces with "-"

Let's only do that in the metric sender's wandb formatting function so we can keep the code clean

**Comment by MathieuSuchet** [comment]
Update: It appears to be a bug on wandb's end, see https://github.com/wandb/wandb/issues/8593
